package org.didd.version;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig versionBeanDaoConfig;

    private final VersionBeanDao versionBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        versionBeanDaoConfig = daoConfigMap.get(VersionBeanDao.class).clone();
        versionBeanDaoConfig.initIdentityScope(type);

        versionBeanDao = new VersionBeanDao(versionBeanDaoConfig, this);

        registerDao(VersionBean.class, versionBeanDao);
    }
    
    public void clear() {
        versionBeanDaoConfig.getIdentityScope().clear();
    }

    public VersionBeanDao getVersionBeanDao() {
        return versionBeanDao;
    }

}
