package org.didd.admob;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import org.didd.admob.IDBean;

import org.didd.admob.IDBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig iDBeanDaoConfig;

    private final IDBeanDao iDBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        iDBeanDaoConfig = daoConfigMap.get(IDBeanDao.class).clone();
        iDBeanDaoConfig.initIdentityScope(type);

        iDBeanDao = new IDBeanDao(iDBeanDaoConfig, this);

        registerDao(IDBean.class, iDBeanDao);
    }
    
    public void clear() {
        iDBeanDaoConfig.getIdentityScope().clear();
    }

    public IDBeanDao getIDBeanDao() {
        return iDBeanDao;
    }

}
